Create Post
makingsensetraining/blog-app-node-react-redux-es6 pull request #2
Opened 2016-11-16 19:27 UTC by juampick

Added moment library for dates, mockBlog api now generates the publishedDate. Created ManagePostPage container component and PostForm component for handling creation. Created actions, and reducer cases to support Post creation

2016-11-16 19:33 UTC, mravinale commented on src/actions/postActions.js
> +        }).catch(error => {
create and update should be using diferent endpoints

2016-11-16 19:35 UTC, mravinale commented on src/components/blog/BlogPage.js
> +                    <Link to="post" className="btn btn-primary" activeClassName="active">
👍

2016-11-16 19:35 UTC, juampick commented on src/actions/postActions.js
> +        }).catch(error => {
Ok perfect, will separate both now ;)

2016-11-16 19:41 UTC, mravinale requested changes

2016-11-16 19:41 UTC, mravinale commented on src/components/blog/PostForm.js
> +export default PostForm;
what do you think about using this plugin for forms? https://github.com/christianalfoni/formsy-react

2016-11-16 19:42 UTC, juampick commented on src/components/blog/PostForm.js
> +export default PostForm;
Yes, I saw it, but for first sprint I thought to finish the complete functionality on traditional way, and after that improve it. But If you like I can do it right now.

2016-11-16 20:03 UTC, mravinale commented on src/actions/postActions.js
> +    };
👍

2016-11-17 19:15 UTC, juampick commented
`Formsy` implemented.
Branch rebased with latest *master* changes. 
Now going to create and call a createPost endpoint.

2016-11-17 19:20 UTC, mravinale approved these changes

2016-11-17 20:31 UTC, merged